### ISSUE TITLE
Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by TimGerlach** [foxundermoon/vs-shell-format#1]
Running the formatter in vscode throws

```
Cannot read property 'substring' of undefined
```

However, after running ``shfmt -w myscript.sh`` once from the command line manually, it worked fine.

**Comment by foxundermoon** [comment]
what  is your system platform and vscode version？
i am just tested on mac os and vscode 1.8

**Comment by TimGerlach** [comment]
Sorry, missed that. I ran it on mac os Sierra with vscode 1.8. After updating to vscode 1.9 recently the issue was gone. Feel free to close.
