### ISSUE TITLE
Support variables in the path

### ISSUE THREAD

**Issue by dmlemos** [foxundermoon/vs-shell-format#10]
Using variables in the path causes an invalid error:
```
"shellformat.path": "${HOME}/go/bin/shfmt"
```
or `${env:HOME}`

Error:
```
the config shellformat.path file not exists please fix it
```

However apart from the error, the extension works fine.

**Comment by foxundermoon** [comment]
do not support variables.
please use absolute path

**Comment by dmlemos** [comment]
Any reason why not? Variables are very useful to work across different workstations. Right now I need to maintain restrict paths on all my machines.

**Comment by foxundermoon** [comment]
this case， you  just need put the shfmt file under system path，and  need not  config shellformat.path
