### ISSUE TITLE
No formatter for 'shellscript'-files installed.

### ISSUE THREAD

**Issue by SiqingYu** [foxundermoon/vs-shell-format#11]
I have installed the shfmt binary release file in `usr/local/bin/shfmt`
I have also installed it using `go get -u github.com/mvdan/sh/cmd/shfmt` in `$HOME/go/bin/shfmt`
I tried set shellformat.path to both paths, but neither worked.

System: Ubuntu 16.04
Go version: 1.9.2
shfmt version: 2.2.0

**Comment by pr4bh4sh** [comment]
`brew install shfmt` worked for me

**Comment by SiqingYu** [comment]
@pr4bh4sh I am using Linux. No brew.

**Comment by foxundermoon** [comment]
download excutable binary file

from https://github.com/mvdan/sh/releases
and config shellformat.path
