### ISSUE TITLE
mac 系统  shfmt我该下载哪一个？

### ISSUE THREAD

**Issue by csc-EricWu** [foxundermoon/vs-shell-format#12]
![image](https://user-images.githubusercontent.com/13517061/35723662-164847b4-0836-11e8-89bf-4e53690845d0.png)

**Comment by foxundermoon** [comment]
64位下载第二个
32位的下载第一个，正常情况都是64位的，很少32位了。

**Comment by mvdan** [comment]
It's also in homebrew: http://formulae.brew.sh/formula/shfmt
