### ISSUE TITLE
"Format Document" does nothing

### ISSUE THREAD

**Issue by thetheodoros** [foxundermoon/vs-shell-format#133]
I've downloaded the latest shfmt executable file for amd64 for windows and set the shellformat.path accordingly so the "shfmt exe not found" error disappeared.

Now when I select "Format Document" nothing happens. No error no logs under "Output" for shellformat.

Am I doing something wrong?

**Comment by MawRojas** [comment]
Did you figure out what was wrong? I also performed the same steps and have the same problem.
