### ISSUE TITLE
Please clarify what the donations are for

### ISSUE THREAD

**Issue by mvdan** [foxundermoon/vs-shell-format#14]
The README mentions many donation methods, saying that they will make shell-format better. Please clarify that these donations won't reach `shfmt`, as I didn't even know anyone was receiving donations for software sitting on top of mine.

To clarify, I don't mind if you do take donations. But please make it clear that the donations may make the *plugin* better, but not the actual shell formatting software that it depends on.

**Comment by foxundermoon** [comment]
This is only used as a test to test whether anyone has actually donated. But I have never received any donations.

**Comment by foxundermoon** [comment]
If I receive a donation, I will send most of it to the author of upstream  `shfmt`
