### ISSUE TITLE
format python jinjia error

### ISSUE THREAD

**Issue by sdliang1013** [foxundermoon/vs-shell-format#159]
when i write a jinjia template for saltstack, it shouldn't format by file extension.
i have a jinjia script named zoo.cfg
{%- if zookeepers_with_ids | length() >1 %}
.................
{%- endif %}
it will be formatted, like this:
{%- if zookeepers_with_ids | length() %} >1
.................
{%- endif %}.

i should disable "properties" in setting "shellformat.effectLanguages" of settings.json

**Comment by foxundermoon** [comment]
```
 "shellformat.effectLanguages": [
	 "shellscript",
	 "dockerfile",
	 "dotenv",
	 "hosts",
	 "jvmoptions",
	 "ignore",
	 "gitignore",
	 "azcli",
	 "bats"
 ]
```
