### ISSUE TITLE
formatting problem with SQLPLUS

### ISSUE THREAD

**Issue by plorenc** [foxundermoon/vs-shell-format#16]
Please take a look at the formatting of code below:

RETVAL='sqlplus -S ${V_ETL_TECH_LOGIN} <<EOF
${SQL_COMMAND}
EOF'

#lines below are green as if they were a part of text above
ERROR_CODE=$?

Lines below are no longer properly formatted (colored). 

The good example of what I mean is to take a look at the Sublime Text editor code. 
Well, to be honest, recently I realized that even in Sublime Text this example is wrongly formatted. It colorize commands like "if" but forget about variables. 
From free editors I use now the best formatting is offered by Notepad++. Please take a look for examples there.

**Comment by foxundermoon** [comment]
enjoy your code😝
