### ISSUE TITLE
piped commands are not formatted

### ISSUE THREAD

**Issue by Toby-Broom** [foxundermoon/vs-shell-format#17]
Hi,

If I write for example:

days=$(echo $1 | perl -ne '/(\d*) day/ && print"$1"')

then the perl -ne is not formatted as expected

Is it possible to make = same class as if, then etc?

how does the recognition of applications work?

**Comment by Toby-Broom** [comment]
Sorry here is clarification:

1. 
Actual:
![actual](https://user-images.githubusercontent.com/27242647/43044809-9e0f3d7c-8dad-11e8-94da-e594b078880b.PNG)
Expected:
![expected](https://user-images.githubusercontent.com/27242647/43044805-8fdbc450-8dad-11e8-8f76-73c6b4d7d8d6.png)

2.

Could I have = colored too?

**Comment by mvdan** [comment]
I don't think this extension does syntax highlighting. If it did, this bug wouldn't exist - `shfmt` parses your program just fine.

**Comment by Toby-Broom** [comment]
OK thanks for comments, looks like I need a syntax highlight add in then ;)
