### ISSUE TITLE
Change 、 to ,

### ISSUE THREAD

**Issue by Sly-Little-Fox** [foxundermoon/vs-shell-format#211]
More readable, looks better. Used wider.

**Comment by foxundermoon** [comment]
thank's your suggestion. can you supply detailed information?

**Comment by Sly-Little-Fox** [comment]
> thank's your suggestion. can you supply detailed information?

`,` is used in almost all languages. There may be problems with fonts when using ` 、` (I guess).

**Comment by dandavison** [comment]
Thanks for the extension @foxundermoon! I've submitted PR https://github.com/foxundermoon/vs-shell-format/pull/263 to make the change that @Sly-Little-Fox is suggesting.
