### ISSUE TITLE
Update VS code and shell-format don't work anymore

### ISSUE THREAD

**Issue by Nounours31** [foxundermoon/vs-shell-format#22]
Hello, sorry I am a newly in Linux (and in english) and I have perhaps make a mistake.
I have updated VS code and it works fine.

I have kept shell-format extension (same place, same options) I have no notification nor errors nor problem in the VS logs.

But I cannot find shell-format command in F1, it does not appears. In terminal I wrote "shfmt -version" and it answer V2.5.0.

Please what can i do to retreive my command?

Thanks a lot,
Pierre

**Comment by foxundermoon** [comment]
#21   the new  version  already remove the command。just use the  formart document command

**Comment by Nounours31** [comment]
Yes I confirm.
Many thanks for your quick answer and for your product which helps me a lot. Really great job. I am studying bash at school and you help me a lot.
Great thanks !
Pierre
