### ISSUE TITLE
[BUG] Unclosed here-document

### ISSUE THREAD

**Issue by jerrygreen** [foxundermoon/vs-shell-format#231]
When I try to use here-document syntax, like this:

![image](https://user-images.githubusercontent.com/13215662/137508675-a87fc0ad-2b62-41b0-8a28-402117303e9d.png)

Or this:

![image](https://user-images.githubusercontent.com/13215662/137508751-a5af5c97-00d5-4459-9d4d-1da826eeaac0.png)

I'm getting this error:

![image](https://user-images.githubusercontent.com/13215662/137509632-2b4cf0c0-14a3-44fb-964c-7f515caf4e2c.png)

Even though this script works just fine, as per doc: https://tldp.org/LDP/abs/html/here-docs.html

**Comment by jerrygreen** [comment]
@foxundermoon maybe instead of silently closing and tagging, you can add some explanation? Why wrong usage?

**Comment by Presac** [comment]
The problem still persists.
