### ISSUE TITLE
Add support for .bats?

### ISSUE THREAD

**Issue by docwhat** [foxundermoon/vs-shell-format#236]
`shfmt`, as of v3.2.0, has support for [`.bats` files](https://github.com/bats-core/bats-core).  Can you add VS Code support for formatting .bats files?

Thanks!

**Comment by foxundermoon** [comment]
I try to test this file  https://raw.githubusercontent.com/bats-core/bats-core/master/test/bats.bats， but failed.
```
bats.bats:13:1: "}" can only be used to close a block
```

**Comment by foxundermoon** [comment]
good suggest.    done #238
