### ISSUE TITLE
Plugin is Too Aggressive at Formatting Non Shell Files (crontabs and others)

### ISSUE THREAD

**Issue by Justintime50** [foxundermoon/vs-shell-format#258]
Why in the world is this tool called `vs-shell-format` if it can format a dozen different syntax/languages? Incredibly misleading and frankly it breaks the DOTW (Do One Thing Well) mantra of software engineering. I digress.

The problem at hand for me is I want to use this plugin to format `shell` scripts only. It's formatting all sorts of other files outside of the traditional `*.sh` files - that may be VS Code's problem and not this plugin. Regardless, I have a `crontab` file that I'm editing in VS Code titled as such, yet it's getting formatted as if it were a shell script. My snippet:

```shell
# The following is the original
0 3 * * * . "$HOME"/.env-crontab; run_some_command > /dev/null

# The following is the output after saving
0 3 * * * . "$HOME"/.env-crontab
run_some_command >/dev/null
```

Crontabs don't support multiple-line commands and thus, this plugin is breaking my crontabs while editing. I've tried adding an `.editorconfig` file that has no effect (I'm not specifying any custom `shfmt` flags, I've checked the `Shellformat: Use Editor Config` checkbox in settings, my editor config looks like the following):

```
[src/crontabs/**]
ignore = true
```

It's incredibly frustrating when a tool doesn't follow the `principle of least surprise` and has odd side-effects that cannot be overridden nor are documented well or at all.

What can I do to fix this or how can we patch this plugin to not be so aggressive at formatting files that it shouldn't?

**Comment by Justintime50** [comment]
Any thoughts on this? It's been 2 months now without any comments.

**Comment by Justintime50** [comment]
5 months is ample time to at least acknowledge this issue. Is there a way I can get this plugin to only format my shell scripts and exclude cron files or not?

**Comment by Justintime50** [comment]
@maxisam my question isn't about `.env` files, it's about crontabs. My config only has the following and it's still formatting `crontab` files when I wouldn't expect it to:

```json
"shellformat.effectLanguages": ["shellscript"],
```

**Comment by maxisam** [comment]
right, my bad. Generally I would use a nicer tone for OSS projects since I usually don't pay anything. 

For you question, I did a quick look in the source code. I don't think there is a way to handle your case. 

I think the author did acknowledge your question with a label.

**Comment by Justintime50** [comment]
Noted. I would have appreciated an explicit answer from the author stating "this isn't possible, we'll consider adding it", or "yes, here is the config on how to do this". Instead, I'm left to wonder if what I'm asking is even possible.

**Comment by maxisam** [comment]
The code is pretty straightforward. https://github.com/foxundermoon/vs-shell-format/blob/41d853411d9a63db8468997638ed39b68929d2a9/src/extension.ts#L35
To do what you want, the author will have to implement pattern and ignore rules.

But I do feel like you might be able to get away by manually change the language on your file to avoid formatting.

<img width="136" alt="image" src="https://user-images.githubusercontent.com/456807/191349670-bcd3ad45-8826-4c0d-81ec-03080e18ba2f.png">

<img width="450" alt="image" src="https://user-images.githubusercontent.com/456807/191349601-bb71bb1b-dd64-41ca-81a0-f4b7d1ccaf17.png">

**Comment by Justintime50** [comment]
I'm going to close this due to lack of engagement.

Some workarounds I'm using: 
1. Use https://marketplace.visualstudio.com/items?itemName=mkhl.shfmt&ssr=false#overview and https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck instead of this plugin
2. Switch my `crontab` file to the `dotenv` language mode which gives close enough syntax highlighting while stopping the plugin from auto formatting it.
