### ISSUE TITLE
Running format breaks Dockerfiles

### ISSUE THREAD

**Issue by mrbrownt** [foxundermoon/vs-shell-format#29]
When running format on Dockerfiles it removes all of the `\` and line endings. This causes RUN commands in docker build to not work.

Runnning shell-format 4.0.4 and shfmt 2.6.3

**Comment by foxundermoon** [comment]
paste your dockerfile

**Comment by JounQin** [comment]
https://github.com/mvdan/sh/issues/424

@foxundermoon It seems Dockerfile is actually not supported by shfmt officially.

**Comment by mattt** [comment]
@foxundermoon Please consider reopening and addressing this issue. When this extension is installed, format-on-save breaks Dockerfiles containing any backslashes (see mvdan/sh#424 as mentioned by @JounQin).

**Comment by JounQin** [comment]
@mattt `binaryNextLine` is auto enabled in `prettier-plugin-sh`, you can use it if you are  using `prettier`.

**Comment by Pointotech** [comment]
If this formatter doesn't support Dockerfiles, why is it formatting Dockerfiles?

**Comment by JukMR** [comment]
Same issue here, this breaks my dockerfiles. It is very problematic that this extensions causes this and the the issue is not resolved yet.
