### ISSUE TITLE
Formatting breaks dockerfiles

### ISSUE THREAD

**Issue by abeMedia** [foxundermoon/vs-shell-format#31]
Remove trailing slashes, causing `RUN` command to fail.

Before format:
```Dockerfile
FROM alpine:3.9
RUN apk add --no-cache \
    bash \
    python \
    py-pip \
  && pip install awscli --upgrade \
  && apk del py-pip
CMD ["/bin/bash"]
```
After format:
```dockerfile
FROM alpine:3.9
RUN apk add --no-cache \
    bash \
    python \
    py-pip &&
pip install awscli --upgrade &&
apk del py-pip
CMD ["/bin/bash"]
```

**Comment by foxundermoon** [comment]
It is good here for me.
```
FROM alpine:3.9
RUN apk add --no-cache \
  bash \
  python \
  py-pip &&
  pip install awscli --upgrade &&
  apk del py-pip
CMD ["/bin/bash"]
```
what  is yout shfmt version ?
`shfmt -version`

**Comment by Gilfar** [comment]
The problem is that the slash is striped after && in your example.
it should have && \
```dockerfile
FROM alpine:3.9
RUN apk add --no-cache \
  bash \
  python \
  py-pip && \
  pip install awscli --upgrade && \
  apk del py-pip
CMD ["/bin/bash"]
```

**Comment by maelvls** [comment]
Looks like [`shfmt`](https://github.com/mvdan/sh) is the culprit. I tried it manually and could reproduce the issue:

The Dockerfile:

```dockerfileFROM alpine:3.9
FROM alpine:3.9
RUN apk add --no-cache \
  bash \
  python \
  py-pip && \
  pip install awscli --upgrade && \
  apk del py-pip
CMD ["/bin/bash"]
```

becomes, with `shfmt -w Dockerfile`:

```dockerfile
FROM alpine:3.9
RUN apk add --no-cache \
	bash \
	python \
	py-pip &&
	pip install awscli --upgrade &&
	apk del py-pip
CMD ["/bin/bash"]
```

I guess we should open an issue upstream 🙂

**Comment by maelvls** [comment]
I found a workaround 🎉 `shfmt` has an option that says

    -bn       binary ops like && and | may start a line

This fixes the above issues!! For example, the above example using `shfmt -bn -w Dockerfile ` is formatted as:

```dockerfile
FROM alpine:3.9
RUN apk add --no-cache \
	bash \
	python \
	py-pip \
	&& pip install awscli --upgrade \
	&& apk del py-pip
CMD ["/bin/bash"]
```

Note: some people prefer starting new lines with `&&` (see https://github.com/moby/moby/issues/16058#issuecomment-334370727). In our case, shfmt will enforce that.
