### ISSUE TITLE
Repeatedly running shell commands in my VS Code Terminal is very annoying

### ISSUE THREAD

**Issue by brandondrew** [foxundermoon/vs-shell-format#33]
1. What is the purpose of this extension frequently opening the VS Code terminal to run shell commands?  (It has happened a few times already today, once when I opened VS Code and later apparently randomly.)

  a. Why must you run the command?
  b. Why so often?
  c. Why in the VS Code Terminal?

2. Is there some other way to achieve any legitimate purposes that does not create such a negative user experience?

**Comment by foxundermoon** [comment]
it may be on the new version vscode bug.

it was run once just after installed.
