### ISSUE TITLE
Formmater replace `` into $()

### ISSUE THREAD

**Issue by Edger** [foxundermoon/vs-shell-format#36]
I want to assign the dns result to `dns_server` by `networksetup -getdnsservers Wi-Fi` in the shellscript, but after I format it, the formatter replace `` into `$()`, show as below:

before format: 
> dns_server=\`networksetup -getdnsservers Wi-Fi\`

after format:   
> dns_server=$(networksetup -getdnsservers Wi-Fi)

**Comment by foxundermoon** [comment]
this is upstream issue，
https://github.com/mvdan/sh/issues
you can query the cause from the author.
I think  `$(…)` is much clearer and easier to use when nesting.

**Comment by Edger** [comment]
@foxundermoon 

Well, the problem is, after the replacement, this command can not execute correctly.

**Comment by kael89** [comment]
@foxundermoon could this issue please be reopened? It seems that `$()` and ` `` ` are not always interchangeable., and converting one to the other may break existing code.

An example:
```bash
input="ap-southeast-2c"

echo `echo $input | sed -e 's:\([0-9]\)[a-z]*\$:\\1:'` #ap-southeast-2
echo $(echo $input | sed -e 's:\([0-9]\)[a-z]*\$:\\1:') #ap-southeast-2c
```
