### ISSUE TITLE
Output to Problems section instead of alert? e.g. function as linter

### ISSUE THREAD

**Issue by iyerusad** [foxundermoon/vs-shell-format#37]
With following flags:
```
"shellformat.flag": "-p"
```

shift + option + L renders following alert:
![image](https://user-images.githubusercontent.com/25647368/58543989-b5c68880-81bd-11e9-97c9-f83f5dbab27b.png)

---

Would it possible to incorporate the `shfmt >/dev/null` behavior (described [here](https://github.com/mvdan/sh#replacing-bash--n)) to show errors in the problems section? Similar to how shellcheck works:
![image](https://user-images.githubusercontent.com/25647368/58544363-54eb8000-81be-11e9-9651-d77eb0a0e49a.png)

**Comment by foxundermoon** [comment]
This is a good suggestion

**Comment by foxundermoon** [comment]
this feature is complete by published version `5.0.0`
