### ISSUE TITLE
cant install shfmt

### ISSUE THREAD

**Issue by alanlivio** [foxundermoon/vs-shell-format#4]
I receive the notification to install shfm using the command `go get -u github.com/mvdan/sh/cmd/shfmt`.
But it doesn't work. I receive the following output.

```
$ go get -u github.com/mvdan/sh/cmd/shfmt
# github.com/mvdan/sh/cmd/shfmt
/opt/go/src/github.com/mvdan/sh/cmd/shfmt/main.go:156: undefined: io.SeekStart
```

**Comment by mvdan** [comment]
`shfmt` requires Go 1.7 or later. See its README: https://github.com/mvdan/sh

**Comment by alanlivio** [comment]
I install go 1.8 and the shfmt is in the PATH.

```
$ go version  
go version go1.8 linux/amd64  
```
```
$ shfmt  -version  
v1.2.0
```
However, the VS code plugin still can't find shfmt and show the message.

`shfmt not found! run go get -u github.com/mvdan/sh/cmd/shfmt to install`

**Comment by foxundermoon** [comment]
@alanlivio   what is your system . i am just test  under  macOs
i'll try virtualize linux and found the reason.

**Comment by alanlivio** [comment]
Thanks by the feedback.
I'm using an Ubuntu 16.04.2 LTS.

**Comment by foxundermoon** [comment]
@alanlivio 
now you can config the shfmt path

eg:  `"shellformat.path": "/usr/local/bin/shfmt"`

**Comment by alanlivio** [comment]
Thanks by the feedback @foxundermoon.
Even shfmt in path the extension doesn't found it.
However its works by setting the shfmt path.

**Comment by Learn-Digital-Audio** [comment]
You probably didn't define the /bin in the path for it can't find the executable.

In Fedora I needed:

```
sudo dnf install golang

mkdir -p $HOME/go
echo 'export GOPATH=$HOME/go' >> $HOME/.bashrc
echo 'export PATH=$PATH:$GOPATH/bin' >> $HOME/.bashrc
source $HOME/.bashrc
```

**Comment by alanlivio** [comment]
Thank you Learn-Digital-Audio.
