### ISSUE TITLE
problems to run the shell format ext

### ISSUE THREAD

**Issue by csjunior** [foxundermoon/vs-shell-format#5]
Hi
I install the shell-format 0.1.3 in the vscode but it don´t run. 
I try to run in the console with format shell with shfmt option but the code in bash and ksh shell is the same and not formated.
My version of the softwares:

C:\Users\claud\t>ver

Microsoft Windows [versão 10.0.14393]

C:\Users\claud\t>go version
go version go1.8 windows/amd64

C:\Users\claud\t>shfmt  -version
v1.2.0

**Comment by csjunior** [comment]
how i get more inforamtions about the execution of the module funcionality in the vscode? With this I can send more informations here!

**Comment by foxundermoon** [comment]
@csjunior  i am not test on window yet.
wait me next version.
it's may be the `shfmt` not in your path

**Comment by foxundermoon** [comment]
@csjunior   update the latest version and  just config
  ` "shellformat.flag": "D:/dev/shfmt_v2.0.0_windows_amd64.exe",` 
 i am tested ,it's well down.
