### ISSUE TITLE
Strange file permissions for binary file.

### ISSUE THREAD

**Issue by feluxe** [foxundermoon/vs-shell-format#50]
Hi there,

I just noticed this, because my backup tool complained that it wasn't allowed to copy `shfmt_v2.6.4_linux_amd64`. I'm wondering what's with the strange permission of that file?

```
$ ls -la ~/.vscode-oss/extensions/foxundermoon.shell-format-6.1.1/bin | grep shfmt

drwxr-xr-x 2 peter peter    4096 Aug 16 13:01 .
drwxr-xr-x 4 peter peter    4096 Aug 16 13:01 ..
--wxrw--wt 1 peter peter 3005216 Aug 16 13:01 shfmt_v2.6.4_linux_amd64
```

**Comment by foxundermoon** [comment]
just use the nodejs to download and give execute permission

**Comment by reini-1** [comment]
I'm not a js/node developer, but I think that you set in Line https://github.com/foxundermoon/vs-shell-format/blob/601cc2a7bdfb7394626ee1a5216d29411ffe5e4a/src/downloader.ts#L241 the wrong permissions.
They should be `0o755` as far as I understand the documentation: https://nodejs.org/api/fs.html#fs_file_modes

Maybe you can fix this.
Thanks in advance.
