### ISSUE TITLE
.env files formatted

### ISSUE THREAD

**Issue by jayco** [foxundermoon/vs-shell-format#53]
Hi - great product.

This works fine when I am using .sh files but it's also formatting my .env files - which is causing my vars to be broken as its splitting strings etc...

**Comment by foxundermoon** [comment]
you can fix the config file.

```diff
"shellformat.effectLanguages": [
  "shellscript",
  "dockerfile",
- "dotenv",
  "hosts",
  "jvmoptions",
  "ignore",
  "gitignore",
  "properties",
  "spring-boot-properties",
  "azcli"
]
```

remove you don't want effect languages
