### ISSUE TITLE
Format Dockerfiles in terminal

### ISSUE THREAD

**Issue by WesleyYue** [foxundermoon/vs-shell-format#57]
Is there a version of the Dockerfile formatter that this extension uses that we could call from the shell for usage on CI?

**Comment by foxundermoon** [comment]
`https://github.com/mvdan/sh/releases`

**Comment by WesleyYue** [comment]
Thanks, I checked out shfmt but it doesn't appear that tool can directly format Dockerfiles (unless I'm missing something). Is this extension doing something on top of that tool to extract the shell commands from the Dockerfile, and then uses shfmt to format those commands?

**Comment by foxundermoon** [comment]
`cat ./Dockerfile | shfmt`

**Comment by WesleyYue** [comment]
Sorry, it seems like I'm still getting different behaviour. When using the extension, I get code formatted like:
```
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    automake
```
Using the command above, I get code like:
```
RUN apt-get update &&
    apt-get install -y --no-install-recommends \
        automake
```

Any idea on how I can match the two output? I tried looking in the code of the extension but couldn't find any flags to shfmt that I think would be causing the difference.
