### ISSUE TITLE
Trojan? 

### ISSUE THREAD

**Issue by yelkarama** [foxundermoon/vs-shell-format#60]
Just got this alert from Windows Defender...

![image](https://user-images.githubusercontent.com/5099215/71606536-b8b49d80-2b3f-11ea-9d07-03496ec6fc6e.png)

Please advise ...

Thanks

**Comment by foxundermoon** [comment]
this is upstream binary format commandline tool

download from  https://github.com/mvdan/sh
```ts
export function getReleaseDownloadUrl() {
  // https://github.com/mvdan/sh/releases/download/v2.6.4/shfmt_v2.6.4_darwin_amd64
  return `https://github.com/mvdan/sh/releases/download/${
    config.shfmtVersion
  }/${getPlatFormFilename()}`;
}
```

the extension is open source.

**Comment by foxundermoon** [comment]
it's downloaded Linux platform tool on windows?
