### ISSUE TITLE
Issues about formatting the shell scripts with "="

### ISSUE THREAD

**Issue by guqiuyuan** [foxundermoon/vs-shell-format#61]
In script,the comparison between string and string.it will be like if [ $1 = "String" ].But use the plugin to format,this will change to if [ $1="String" ],this behaviour will change the result of this expression.

**Comment by foxundermoon** [comment]
before

```
if [ $1 						= "String" ]; then
	echo eq
fi

```

after
```bash
if [ $1 = "String" ]; then
	echo eq
fi
```
