### ISSUE TITLE
How to disable formatting for Dockerfile?

### ISSUE THREAD

**Issue by zulhfreelancer** [foxundermoon/vs-shell-format#62]
Hi,

I've been using this extension for a while and I like it. But for Dockerfile, I prefer not to enable the auto formatting.

How to disable it?

Thanks.

**Comment by foxundermoon** [comment]
```diff
"shellformat.effectLanguages": [
            "shellscript",
-            "dockerfile",
            "dotenv",
            "hosts",
            "jvmoptions",
            "ignore",
            "gitignore",
            "properties",
            "spring-boot-properties",
            "azcli"
          ]
```

**Comment by Eisbrenner** [comment]
Hi,

I, too, liked to disable the formatting for Dockerfiles since it removes `\` at the end of lines, which breaks the files.

However, since I had format-on-save enabled, I needed to add 

```
"[dockerfile]": {
    "editor.formatOnSave": false,
},
"shellformat.effectLanguages": [
    "shellscript",
    // ... excluding dockerfile
]
```

having either of those excluded from the settings would result in auto formatting of Dockerfiles.

**Comment by foxundermoon** [comment]
@Eisbrenner    Maybe it was formatted by another plugin

**Comment by joemaller** [comment]
@foxundermoon Dropped backslashes in Dockerfiles seems to be happening upstream in `shfmt`. My Dockerfiles weren't formatting (because of Prettier?) until I explicitly enabled shell-format in settings.json with this:

```json
    "[dockerfile]": {
        "editor.defaultFormatter": "foxundermoon.shell-format"
    }
```

After that, my Dockerfiles formatted, but all multi-line commands broke. Output from this extension (obviously?) is identical to output from `shfmt`. 

**Input**
```dockerfile
RUN yum -y -q update \
        && yum install -q -y zip
```
**output**
```dockerfile
RUN yum -y -q update &&
	yum install -q -y zip
```

**Comment by joemaller** [comment]
Followup: This should be a known issue and was already mentioned here in #29 which referenced mvdan/sh#424

**Comment by texastoland** [comment]
@foxundermoon Your extension shouldn't manually format files. It also ignores `.vscode/settings.json`. `formatOnSave` happens automatically when you register as a formatter. Could you please remove the following lines:

https://github.com/foxundermoon/vs-shell-format/blob/9af1d95d6403603f33dcee49965f6447fe385c8c/src/extension.ts#L43-L52

**Comment by bernardolm** [comment]
> ```diff
> "shellformat.effectLanguages": [
>             "shellscript",
> -            "dockerfile",
>             "dotenv",
>             "hosts",
>             "jvmoptions",
>             "ignore",
>             "gitignore",
>             "properties",
>             "spring-boot-properties",
>             "azcli"
>           ]
> ```

Doesn't work for me

**Comment by JounQin** [comment]
`binaryNextLine` is auto enabled in `prettier-plugin-sh`, you can use it if you are  using `prettier`.

**Comment by bduffany** [comment]
@foxundermoon It looks like those lines mentioned in https://github.com/foxundermoon/vs-shell-format/issues/62#issuecomment-639314549 are still in the code?

**Comment by Re-st** [comment]
I happened to have same issue. After some struggles I evaded the problem by installing Docker extension and setting dockerfile default formatter to the one given there.

**Comment by rucoder** [comment]
I managed to fix it adding following to my settings.json
```
    "[dockerfile]": {
        "editor.defaultFormatter": "foxundermoon.shell-format"
    },
   "shellformat.flag": "-bn"
```

**Comment by JounQin** [comment]
I think the solution should be well documented.

**Comment by Pointotech** [comment]
This extension should not be attempting to format Dockefiles, since it clearly isn't able to do so correctly and it doesn't seem to be the goal of this extension.

There should not be extra configuration required to avoid breaking files which this extension doesn't support.
