### ISSUE TITLE
No error message when using keyboard shortcut

### ISSUE THREAD

**Issue by David-Else** [foxundermoon/vs-shell-format#7]
Hello, thanks for this wonderful extension!

I am using VS Code Version 1.13.1 on Linux Fedora 25

When i use the format short-cut 'Shift+Ctrl I' if there are no errors it formats. If there are errors then nothing happens!

If I press F1 and select 'format shell with shfmt' then I see the error message appear that should also appear when I press the shortcut.

Thanks :)

**Comment by foxundermoon** [comment]
@David-Else   yeah ,i  will add error tips for default format

**Comment by foxundermoon** [comment]
@David-Else  v1.1.0  has the feature.

**Comment by David-Else** [comment]
Awesome! :)
