### ISSUE TITLE
multiple runs cause extra newlines

### ISSUE THREAD

**Issue by PanovEduard** [foxundermoon/vs-shell-format#8]
for example: you have script:
 **[ ... ] \\
  && {...;}**
after first run with -bn you'll get
**[ ... ] \\
\\
&& {...;}**
after second:
**[ ... ] \\
\\
\\
&& {...;}**
and so on...

**Comment by PanovEduard** [comment]
it happens even without -bn

**Comment by foxundermoon** [comment]
@PanovEduard  i am try with default setting ` "shellformat.flag": null`  but not occurs .  it just warp the shfmt ,   you can issue  @https://github.com/mvdan/sh
