### ISSUE TITLE
Formatting problem

### ISSUE THREAD

**Issue by nmarghetti** [foxundermoon/vs-shell-format#92]
Hello,

I have started using recently this extension which I find really awesome.
Everything was working fine until I worked on a file with tricky writing, multi lines command with inline comments:

```bash
#! /bin/bash
echo yargs \
    react-test-renderer `# Test react rendering` \
        chalk `# Log with color` \
    morgan `# Log HTTP request in the console`

```

The above scripts cannot be formatted by the extension, the linter gives this error on the last empty line: "6:12: reached EOF without closing quote `"

However, the following content (adding comments after "echo yargs"):

```bash
#! /bin/bash

echo yargs `# parse args` \
    react-test-renderer `# Test react rendering` \
        chalk `# Log with color` \
    morgan `# Log HTTP request in the console`

```
 is getting formatted like this:

```bash
#! /bin/bash

echo yargs $(# parse args` \
  react-test-renderer
) \
  chalk $(# Test react rendering` \
    # Log with color` \
    morgan
  ) # Log HTTP request in the console`

```

So either the formatting does not work, either it is formatting not in the expected way.

Do you have any idea about this problem ?
Should I not write such code ?
Is it a limitation or a bug ?

**Comment by nmarghetti** [comment]
Here are some details about my environment

Visual Studio Code:
Version: 1.44.1
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

shell-format version 7.0.1

**Comment by nmarghetti** [comment]
I found a solution to handle what I wanted:

```bash
#! /bin/bash

args=(
  react-test-renderer # Test react rendering
  chalk               # Log with color
  morgan              # Log HTTP request in the console
)
yarn add "${args[@]}"
```

But still, what do you think about the behavior described first ?

**Comment by foxundermoon** [comment]
shfmt does not support the syntax of inline comments
